# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default combo is a good baseline.
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone =

sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/quizforge

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(name)s] %(levelname)-5.5s: %(message)s
datefmt = %H:%M:%S
